"""Create initial tables

Revision ID: 60cabfd29874
Revises:
Create Date: 2025-04-16 15:33:56.024119

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60cabfd29874"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keywords_id"), "keywords", ["id"], unique=False)
    op.create_index(op.f("ix_keywords_keyword"), "keywords", ["keyword"], unique=True)
    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("plot_points", sa.String(), nullable=True),
        sa.Column("characters", sa.String(), nullable=True),
        sa.Column("locations", sa.String(), nullable=True),
        sa.Column("items", sa.String(), nullable=True),
        sa.Column("estimated_duration", sa.String(), nullable=True),
        sa.Column("rpg_system", sa.String(), nullable=True),
        sa.Column("theme", sa.String(), nullable=True),
        sa.Column("player_count", sa.Integer(), nullable=True),
        sa.Column("complexity", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stories_id"), "stories", ["id"], unique=False)
    op.create_index(op.f("ix_stories_title"), "stories", ["title"], unique=False)
    op.create_table(
        "story_keyword",
        sa.Column("story_id", sa.Integer(), nullable=True),
        sa.Column("keyword_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keywords.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_keyword")
    op.drop_index(op.f("ix_stories_title"), table_name="stories")
    op.drop_index(op.f("ix_stories_id"), table_name="stories")
    op.drop_table("stories")
    op.drop_index(op.f("ix_keywords_keyword"), table_name="keywords")
    op.drop_index(op.f("ix_keywords_id"), table_name="keywords")
    op.drop_table("keywords")
    # ### end Alembic commands ###
